// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tahlilgaran.Data;

#nullable disable

namespace Tahlilgaran.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260624053458_addadminseed")]
    partial class addadminseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("Tahlilgaran.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            Password = "PBKDF2-SHA256$210000$Eacy+aiNebR/YNY0V3gwNg==$ClM5SDUXnEplRrLILfTPJvKTEx7ngH04HVM1PF2fCp4=",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
